# Generated by Django 2.0.6 on 2021-01-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=128)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('age', models.SmallIntegerField()),
                ('img', models.ImageField(default='img/1.jpg', upload_to='img')),
            ],
            options={
                'verbose_name': '员工表',
                'verbose_name_plural': '员工表',
                'db_table': 'bz_emp',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=64)),
                ('re_name', models.CharField(max_length=64)),
                ('sex', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0)),
                ('status', models.BooleanField(default=True)),
                ('register_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'bz_user',
            },
        ),
    ]
